apiVersion: v1
kind: Service
metadata:
  name: docknet
spec:
  type: NodePort
  selector:
    app: docknet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: pgweb
spec:
  type: NodePort
  selector:
    app: pgweb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30012

---

apiVersion: v1
kind: Service
metadata:
  name: s3
spec:
  type: ClusterIP
  selector:
    app: s3
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---

apiVersion: v1
kind: Service
metadata:
  name: docknet-extension-workspace
spec:
  type: ClusterIP
  selector:
    app: docknet-extension-workspace
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

